# Generated by Django 3.2.8 on 2021-10-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnxDump',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('source_addr', models.CharField(max_length=9)),
                ('destination_addr', models.CharField(max_length=9)),
                ('apci', models.CharField(max_length=50)),
                ('tpci', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=6)),
                ('repeated', models.IntegerField()),
                ('hop_count', models.PositiveIntegerField()),
                ('apdu', models.TextField(blank=True, null=True)),
                ('payload_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cemi', models.TextField(blank=True, null=True)),
                ('payload_data', models.CharField(blank=True, max_length=100, null=True)),
                ('is_manipulated', models.IntegerField()),
                ('attack_type_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knx_dump',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogKzh',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('source_addr', models.CharField(blank=True, max_length=9, null=True)),
                ('destination_addr', models.CharField(blank=True, max_length=9, null=True)),
                ('extended_frame', models.PositiveIntegerField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=6, null=True)),
                ('repeat', models.PositiveIntegerField(blank=True, null=True)),
                ('ack_req', models.PositiveIntegerField(blank=True, null=True)),
                ('confirm', models.PositiveIntegerField(blank=True, null=True)),
                ('system_broadcast', models.PositiveIntegerField(blank=True, null=True)),
                ('hop_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tpci', models.CharField(blank=True, max_length=25, null=True)),
                ('tpci_sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('apci', models.CharField(blank=True, max_length=50, null=True)),
                ('payload_data', models.CharField(blank=True, max_length=256, null=True)),
                ('payload_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_manipulated', models.PositiveIntegerField()),
                ('attack_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sensor_addr', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'log_kzh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogKzhOld',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('source_addr', models.CharField(blank=True, max_length=9, null=True)),
                ('destination_addr', models.CharField(blank=True, max_length=9, null=True)),
                ('apci', models.CharField(blank=True, max_length=50, null=True)),
                ('tpci', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.CharField(blank=True, max_length=6, null=True)),
                ('repeated', models.IntegerField(blank=True, null=True)),
                ('hop_count', models.PositiveIntegerField(blank=True, null=True)),
                ('apdu', models.TextField(blank=True, null=True)),
                ('payload_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cemi', models.TextField(blank=True, null=True)),
                ('payload_data', models.CharField(blank=True, max_length=100, null=True)),
                ('is_manipulated', models.IntegerField()),
                ('attack_type_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sensor_addr', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'log_kzh_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnknownTelegram',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('cemi', models.TextField(blank=True, null=True)),
                ('sensor_addr', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'unknown_telegram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destination_Addr',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('destination_addr', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Source_Addr',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('source_addr', models.CharField(max_length=20)),
            ],
        ),
    ]
