# Generated by Django 3.2.8 on 2021-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211021_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueDestinationAddr',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueSourceAddr',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='destinationaddr',
            old_name='destination_addr',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='sourceaddr',
            old_name='source_addr',
            new_name='address',
        ),
    ]
