# Generated by Django 3.2.8 on 2021-10-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20211021_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquedestinationaddr',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uniquesourceaddr',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
