# Generated by Django 3.2.8 on 2021-10-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211021_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniquedestinationaddr',
            name='address',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='uniquesourceaddr',
            name='address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
