# Generated by Django 3.2.8 on 2021-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211021_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceToDestination',
            fields=[
                ('sequence_number', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_addr', models.CharField(max_length=20, unique=True)),
                ('destination_addr', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
