# Generated by Django 3.2.8 on 2021-10-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_sourcetodestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetodestination',
            name='destination_addr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sourcetodestination',
            name='source_addr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sourcetodestination',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
