# Generated by Django 3.2.8 on 2021-10-23 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_uniquedestinationaddr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquesourceaddr',
            options={'ordering': ['-address']},
        ),
    ]
