# Generated by Django 3.2.8 on 2021-10-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_uniquesourceaddr_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uniquedestinationaddr',
            options={'ordering': ['address']},
        ),
        migrations.AlterModelOptions(
            name='uniquesourceaddr',
            options={'ordering': ['address']},
        ),
    ]
